### ISSUE TITLE
duplicate project / package

### ISSUE THREAD

**Issue by nkappler** [itsjavi/ra-data-treeql#2]
Hi, have you seen the original project?

https://github.com/mevdschee/ra-data-treeql

@mevdschee and I have done some work there already to a point where the dataprovider was very usable already.

Meybe we should consolidate those repositories.

What do you think?

**Comment by itsjavi** [comment]
Hello, one thing that I saw that the other project was missing was the auto-generation, which is provided by this one.

You are free to remix this work into the other project since I am not actively maintaining it at the moment (and I don't plan to add RA 4.0 support soon).

**Comment by itsjavi** [comment]
Unfortunately, I don't have the time to do all the work that requires readapting this package.

I could though publish it under another name (and deprecate the current package) if there is a working PR that reuses your package while keeping the same functionality as this one.

Also, I'd consider taking a look at how I implemented filtering and the implementation of the RA crud API, it may give you some ideas for improvements in your package.

I think `ra-admin-guesser-treeql` would be a good name, because It will still need the TreeQL endpoints.

**Comment by nkappler** [comment]
If you want you can add me as a maintainer on npm or transfer the package to my user [nkappler](https://www.npmjs.com/~nkappler)
https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account#transferring-a-package-from-a-user-account-to-another-user-account-on-the-website

I would then release a new major version for the package, indicating breaking changes.
After that, you can re-publish your package with the new name and take all the time you need to refactor it.

This way the package doesn't need to be dreprecated (which wouldn't resolve the naming conflict I believe)

>Also, I'd consider taking a look at how I implemented filtering and the implementation of the RA crud API, it may give you some ideas for improvements in your package.

Thanks, @mevdschee has published an update on php-crud-api last week which supports the search (`q`) parameter.
I am currently working on integrating this together with suffix-based [filter operators](https://marmelab.com/react-admin/FilteringTutorial.html#filter-operators)

**Comment by nkappler** [comment]
any updates so far...? 😊

**Comment by nkappler** [comment]
thanks, will do :)
I'll close this issue, once I am done

**Comment by nkappler** [comment]
just published 1.0.0
@mevdschee I've pointed it to my fork for now.

**Comment by itsjavi** [comment]
thanks, there was no need though, to remove me as a maintainer

**Comment by itsjavi** [comment]
you also have to edit the pages in the React Admin website, to point to the right repo https://marmelab.com/react-admin/DataProviderList.html

**Comment by mevdschee** [comment]
>thanks, there was no need though, to remove me as a maintainer

agree

**Comment by nkappler** [comment]
>thanks, there was no need though, to remove me as a maintainer

My fault, sorry for the misunderstanding, I've invited you back in 🙂

**Comment by nkappler** [comment]
>you also have to edit the pages in the React Admin website, to point to the right repo https://marmelab.com/react-admin/DataProviderList.html

Thank you, I remembered the list but didn't know where to change it yesterday.
I've filed a [Pull Request](https://github.com/marmelab/react-admin/pull/7808)
